# encoding: UTF-8

from objectmaphelper import *

mainWindow_QQuickApplicationWindow = {"name": "mainWindow", "type": "QQuickApplicationWindow", "visible": True}
mainWindow_dialogBackground_Rectangle = {"container": mainWindow_QQuickApplicationWindow, "id": "dialogBackground", "type": "Rectangle", "unnamed": 1, "visible": True}
mainWindow_border_Rectangle = {"container": mainWindow_QQuickApplicationWindow, "id": "border", "occurrence": 2, "type": "Rectangle", "unnamed": 1, "visible": True}
mainWindow_button_Button = {"checkable": False, "container": mainWindow_QQuickApplicationWindow, "id": "button", "occurrence": 10, "type": "Button", "unnamed": 1, "visible": True}
mainWindow_border_Rectangle_2 = {"container": mainWindow_QQuickApplicationWindow, "id": "border", "occurrence": 4, "type": "Rectangle", "unnamed": 1, "visible": True}
mainWindow_Overlay = {"container": mainWindow_QQuickApplicationWindow, "type": "Overlay", "unnamed": 1, "visible": True}
pediatric_Label = {"container": mainWindow_Overlay, "text": "Pediatric", "type": "Label", "unnamed": 1, "visible": True}
female_Label = {"container": mainWindow_Overlay, "text": "Female", "type": "Label", "unnamed": 1, "visible": True}
mainWindow_decreaseButton_Button = {"checkable": False, "container": mainWindow_QQuickApplicationWindow, "id": "decreaseButton", "type": "Button", "unnamed": 1, "visible": True}
mainWindow_10_BlinkingLabel = {"container": mainWindow_QQuickApplicationWindow, "text": 10, "type": "BlinkingLabel", "unnamed": 1, "visible": True}
mainWindow_increaseButton_Button = {"checkable": False, "container": mainWindow_QQuickApplicationWindow, "id": "increaseButton", "type": "Button", "unnamed": 1, "visible": True}
mainWindow_border_Rectangle_3 = {"container": mainWindow_QQuickApplicationWindow, "id": "border", "occurrence": 8, "type": "Rectangle", "unnamed": 1, "visible": True}
mainWindow_button_Button_2 = {"checkable": False, "container": mainWindow_QQuickApplicationWindow, "id": "button", "occurrence": 3, "type": "Button", "unnamed": 1, "visible": True}
mainWindow_1_min_Label = {"container": mainWindow_QQuickApplicationWindow, "text": "1/min", "type": "Label", "unnamed": 1, "visible": True}
mainWindow_15_Label = {"container": mainWindow_QQuickApplicationWindow, "occurrence": 5, "text": 15, "type": "Label", "unnamed": 1, "visible": True}
mainWindow_buttonBackground_Rectangle = {"container": mainWindow_QQuickApplicationWindow, "id": "buttonBackground", "occurrence": 2, "type": "Rectangle", "unnamed": 1, "visible": True}
mainWindow_20_BlinkingLabel = {"container": mainWindow_QQuickApplicationWindow, "text": 20, "type": "BlinkingLabel", "unnamed": 1, "visible": True}
mainWindow_20_Label = {"container": mainWindow_QQuickApplicationWindow, "occurrence": 5, "text": 20, "type": "Label", "unnamed": 1, "visible": True}
mainWindow_patientInfoColumn_Rectangle = {"container": mainWindow_QQuickApplicationWindow, "id": "patientInfoColumn", "type": "Rectangle", "unnamed": 1, "visible": True}
mainWindow_button_Button_3 = {"checkable": False, "container": mainWindow_QQuickApplicationWindow, "id": "button", "occurrence": 4, "type": "Button", "unnamed": 1, "visible": True}
mainWindow_Cancel_StyledButton = {"checkable": False, "container": mainWindow_QQuickApplicationWindow, "id": "cancelButton", "text": "Cancel", "type": "StyledButton", "unnamed": 1, "visible": True}
o_SystemTray = {"type": "SystemTray"}
mainWindow_background_Rectangle = {"container": mainWindow_QQuickApplicationWindow, "id": "background", "occurrence": 9, "type": "Rectangle", "unnamed": 1, "visible": True}
mainWindow_10_Label = {"container": mainWindow_QQuickApplicationWindow, "occurrence": 5, "text": 10, "type": "Label", "unnamed": 1, "visible": True}
mainWindow_buttonBackground_Rectangle_2 = {"container": mainWindow_QQuickApplicationWindow, "id": "buttonBackground", "occurrence": 3, "type": "Rectangle", "unnamed": 1, "visible": True}
mainWindow_300_BlinkingLabel = {"container": mainWindow_QQuickApplicationWindow, "text": 300, "type": "BlinkingLabel", "unnamed": 1, "visible": True}
mainWindow_300_Label = {"container": mainWindow_QQuickApplicationWindow, "occurrence": 4, "text": 300, "type": "Label", "unnamed": 1, "visible": True}
mainWindow_9_0_BlinkingLabel = {"container": mainWindow_QQuickApplicationWindow, "text": "9.0", "type": "BlinkingLabel", "unnamed": 1, "visible": True}
mainWindow_245_BlinkingLabel = {"container": mainWindow_QQuickApplicationWindow, "text": 245, "type": "BlinkingLabel", "unnamed": 1, "visible": True}
mainWindow_mL_Label = {"container": mainWindow_QQuickApplicationWindow, "text": "mL", "type": "Label", "unnamed": 1, "visible": True}
mainWindow_button_Button_4 = {"checkable": False, "container": mainWindow_QQuickApplicationWindow, "id": "button", "occurrence": 6, "type": "Button", "unnamed": 1, "visible": True}
neonate_Label = {"container": mainWindow_Overlay, "text": "Neonate", "type": "Label", "unnamed": 1, "visible": True}
mainWindow_button_Button_5 = {"checkable": False, "container": mainWindow_QQuickApplicationWindow, "id": "button", "occurrence": 11, "type": "Button", "unnamed": 1, "visible": True}
shorcut_1_Label = {"container": mainWindow_Overlay, "text": "Shorcut 1", "type": "Label", "unnamed": 1, "visible": True}
pC_Label = {"container": mainWindow_Overlay, "text": "PC", "type": "Label", "unnamed": 1, "visible": True}
itemDelegate_ItemDelegate = {"checkable": False, "container": mainWindow_Overlay, "id": "itemDelegate", "occurrence": 3, "type": "ItemDelegate", "unnamed": 1, "visible": True}
mainWindow_44_BlinkingLabel = {"container": mainWindow_QQuickApplicationWindow, "text": 44, "type": "BlinkingLabel", "unnamed": 1, "visible": True}
mainWindow_0_152_BlinkingLabel = {"container": mainWindow_QQuickApplicationWindow, "text": "0.152", "type": "BlinkingLabel", "unnamed": 1, "visible": True}
mainWindow_buttonBackground_Rectangle_3 = {"container": mainWindow_QQuickApplicationWindow, "id": "buttonBackground", "occurrence": 6, "type": "Rectangle", "unnamed": 1, "visible": True}
mainWindow_Label = {"container": mainWindow_QQuickApplicationWindow, "text": "%", "type": "Label", "unnamed": 1, "visible": True}
mainWindow_s_Label = {"container": mainWindow_QQuickApplicationWindow, "occurrence": 2, "text": "s", "type": "Label", "unnamed": 1, "visible": True}
mainWindow_buttonBackground_Rectangle_4 = {"container": mainWindow_QQuickApplicationWindow, "id": "buttonBackground", "occurrence": 9, "type": "Rectangle", "unnamed": 1, "visible": True}
mainWindow_3_0_BlinkingLabel = {"container": mainWindow_QQuickApplicationWindow, "occurrence": 2, "text": "3.0", "type": "BlinkingLabel", "unnamed": 1, "visible": True}
mainWindow_10_BlinkingLabel_2 = {"container": mainWindow_QQuickApplicationWindow, "occurrence": 2, "text": 10, "type": "BlinkingLabel", "unnamed": 1, "visible": True}
mainWindow_flickable_Flickable = {"container": mainWindow_QQuickApplicationWindow, "id": "flickable", "occurrence": 4, "type": "Flickable", "unnamed": 1, "visible": True}
flickable_buttonBackground_Rectangle = {"container": mainWindow_flickable_Flickable, "id": "buttonBackground", "type": "Rectangle", "unnamed": 1, "visible": True}
flickable_31_PatientDataBlinkingLabel = {"container": mainWindow_flickable_Flickable, "text": 31, "type": "PatientDataBlinkingLabel", "unnamed": 1, "visible": True}
flickable_10_PatientDataBlinkingLabel = {"container": mainWindow_flickable_Flickable, "text": 10, "type": "PatientDataBlinkingLabel", "unnamed": 1, "visible": True}
flickable_buttonBackground_Rectangle_2 = {"container": mainWindow_flickable_Flickable, "id": "buttonBackground", "occurrence": 4, "type": "Rectangle", "unnamed": 1, "visible": True}
flickable_buttonBackground_Rectangle_3 = {"container": mainWindow_flickable_Flickable, "id": "buttonBackground", "occurrence": 5, "type": "Rectangle", "unnamed": 1, "visible": True}
flickable_P_Label = {"container": mainWindow_flickable_Flickable, "text": "P", "type": "Label", "unnamed": 1, "visible": True}
flickable_BreathBarButton = {"checkable": False, "container": mainWindow_flickable_Flickable, "type": "BreathBarButton", "unnamed": 1, "visible": True}
mainWindow_button_Button_6 = {"checkable": False, "container": mainWindow_QQuickApplicationWindow, "id": "button", "occurrence": 5, "type": "Button", "unnamed": 1, "visible": True}
mainWindow_Close_StyledButton = {"checkable": False, "container": mainWindow_QQuickApplicationWindow, "id": "closeButton", "text": "Close", "type": "StyledButton", "unnamed": 1, "visible": True}
mainWindow_border_Rectangle_4 = {"container": mainWindow_QQuickApplicationWindow, "id": "border", "occurrence": 7, "type": "Rectangle", "unnamed": 1, "visible": True}
mainWindow_dismissButton_ToolButton = {"checkable": False, "container": mainWindow_QQuickApplicationWindow, "id": "dismissButton", "occurrence": 2, "type": "ToolButton", "unnamed": 1, "visible": True}
mainWindow_dismissButton_ToolButton_2 = {"checkable": False, "container": mainWindow_QQuickApplicationWindow, "id": "dismissButton", "type": "ToolButton", "unnamed": 1, "visible": True}
mainWindow_border_Rectangle_5 = {"container": mainWindow_QQuickApplicationWindow, "id": "border", "occurrence": 6, "type": "Rectangle", "unnamed": 1, "visible": True}
flickable_18_PatientDataBlinkingLabel = {"container": mainWindow_flickable_Flickable, "text": 18, "type": "PatientDataBlinkingLabel", "unnamed": 1, "visible": True}
flickable_buttonBackground_Rectangle_4 = {"container": mainWindow_flickable_Flickable, "id": "buttonBackground", "occurrence": 2, "type": "Rectangle", "unnamed": 1, "visible": True}
flickable_buttonBackground_Rectangle_5 = {"container": mainWindow_flickable_Flickable, "id": "buttonBackground", "occurrence": 3, "type": "Rectangle", "unnamed": 1, "visible": True}
flickable_1_5_0_PatientDataBlinkingLabel = {"container": mainWindow_flickable_Flickable, "text": "1:5.0", "type": "PatientDataBlinkingLabel", "unnamed": 1, "visible": True}
flickable_6_2_PatientDataBlinkingLabel = {"container": mainWindow_flickable_Flickable, "text": "6.2", "type": "PatientDataBlinkingLabel", "unnamed": 1, "visible": True}
flickable_buttonBackground_Rectangle_6 = {"container": mainWindow_flickable_Flickable, "id": "buttonBackground", "occurrence": 6, "type": "Rectangle", "unnamed": 1, "visible": True}
flickable_7_1_PatientDataBlinkingLabel = {"container": mainWindow_flickable_Flickable, "text": "7.1", "type": "PatientDataBlinkingLabel", "unnamed": 1, "visible": True}
mainWindow_buttonBackground_Rectangle_5 = {"container": mainWindow_QQuickApplicationWindow, "id": "buttonBackground", "occurrence": 5, "type": "Rectangle", "unnamed": 1, "visible": True}
mainWindow_Rectangle = {"container": mainWindow_QQuickApplicationWindow, "occurrence": 201, "type": "Rectangle", "unnamed": 1, "visible": True}
mainWindow_9_8_Label = {"container": mainWindow_QQuickApplicationWindow, "occurrence": 3, "text": "9.8", "type": "Label", "unnamed": 1, "visible": True}
mainWindow_12_Label = {"container": mainWindow_QQuickApplicationWindow, "occurrence": 3, "text": 12, "type": "Label", "unnamed": 1, "visible": True}
mainWindow_settingButton_BoundedSettingButton = {"checkable": False, "container": mainWindow_QQuickApplicationWindow, "id": "settingButton", "type": "BoundedSettingButton", "unnamed": 1, "visible": True}
mainWindow_Cancel_StyledButton_2 = {"checkable": False, "container": mainWindow_QQuickApplicationWindow, "id": "cancelButton", "occurrence": 2, "text": "Cancel", "type": "StyledButton", "unnamed": 1, "visible": True}
mainWindow_Close_Dialog_StyledButton = {"checkable": False, "container": mainWindow_QQuickApplicationWindow, "id": "yesButton", "text": "Close Dialog", "type": "StyledButton", "unnamed": 1, "visible": True}
mainWindow_25_BlinkingLabel = {"container": mainWindow_QQuickApplicationWindow, "text": 25, "type": "BlinkingLabel", "unnamed": 1, "visible": True}
mainWindow_250_BlinkingLabel = {"container": mainWindow_QQuickApplicationWindow, "text": 250, "type": "BlinkingLabel", "unnamed": 1, "visible": True}
mainWindow_30_BlinkingLabel = {"container": mainWindow_QQuickApplicationWindow, "text": 30, "type": "BlinkingLabel", "unnamed": 1, "visible": True}
mainWindow_310_BlinkingLabel = {"container": mainWindow_QQuickApplicationWindow, "text": 310, "type": "BlinkingLabel", "unnamed": 1, "visible": True}
mainWindow_12_BlinkingLabel = {"container": mainWindow_QQuickApplicationWindow, "text": 12, "type": "BlinkingLabel", "unnamed": 1, "visible": True}
mainWindow_320_BlinkingLabel = {"container": mainWindow_QQuickApplicationWindow, "text": 320, "type": "BlinkingLabel", "unnamed": 1, "visible": True}
mainWindow_background_Rectangle_2 = {"container": mainWindow_QQuickApplicationWindow, "id": "background", "type": "Rectangle", "unnamed": 1, "visible": True}
speakers_100_Button = {"container": o_SystemTray, "text": "Speakers: 100%", "type": "Button"}
mainWindow_INV_Label = {"container": mainWindow_QQuickApplicationWindow, "occurrence": 2, "text": "INV", "type": "Label", "unnamed": 1, "visible": True}
mainWindow_50kg_Label = {"container": mainWindow_QQuickApplicationWindow, "text": "50kg", "type": "Label", "unnamed": 1, "visible": True}
mainWindow_button_Button_7 = {"checkable": False, "container": mainWindow_QQuickApplicationWindow, "id": "button", "occurrence": 12, "type": "Button", "unnamed": 1, "visible": True}
user_Training_Label = {"container": mainWindow_Overlay, "text": "User Training", "type": "Label", "unnamed": 1, "visible": True}
mainWindow_image_IconImage = {"container": mainWindow_QQuickApplicationWindow, "objectName": "image", "source": "qrc:/images/icons/help/close_help.svg", "type": "IconImage", "visible": True}
mainWindow_Rectangle_2 = {"container": mainWindow_QQuickApplicationWindow, "occurrence": 58, "type": "Rectangle", "unnamed": 1, "visible": True}
mainWindow_Continue_StyledButton = {"container": mainWindow_QQuickApplicationWindow, "occurrence": 195, "type": "Rectangle", "unnamed": 1, "visible": True}
male_Label = {"container": mainWindow_Overlay, "text": "Male", "type": "Label", "unnamed": 1, "visible": True}
itemDelegate_ItemDelegate_2 = {"checkable": False, "container": mainWindow_Overlay, "id": "itemDelegate", "type": "ItemDelegate", "unnamed": 1, "visible": True}
mainWindow_180_BlinkingLabel = {"container": mainWindow_QQuickApplicationWindow, "text": 180, "type": "BlinkingLabel", "unnamed": 1, "visible": True}
mainWindow_26_BlinkingLabel = {"container": mainWindow_QQuickApplicationWindow, "text": 26, "type": "BlinkingLabel", "unnamed": 1, "visible": True}
mainWindow_3_0_BlinkingLabel_2 = {"container": mainWindow_QQuickApplicationWindow, "text": "3.0", "type": "BlinkingLabel", "unnamed": 1, "visible": True}
mainWindow_100_BlinkingLabel = {"container": mainWindow_QQuickApplicationWindow, "text": 100, "type": "BlinkingLabel", "unnamed": 1, "visible": True}
mainWindow_0_0_BlinkingLabel = {"container": mainWindow_QQuickApplicationWindow, "text": "0.0", "type": "BlinkingLabel", "unnamed": 1, "visible": True}
mainWindow_BlinkingLabel = {"container": mainWindow_QQuickApplicationWindow, "text": "", "type": "BlinkingLabel", "unnamed": 1, "visible": True}
mainWindow_40_BlinkingLabel = {"container": mainWindow_QQuickApplicationWindow, "text": 40, "type": "BlinkingLabel", "unnamed": 1, "visible": True}
mainWindow_VC_Label = {"container": mainWindow_QQuickApplicationWindow, "text": "VC", "type": "Label", "unnamed": 1, "visible": True}
itemDelegate_ItemDelegate_3 = {"checkable": False, "container": mainWindow_Overlay, "id": "itemDelegate", "occurrence": 2, "type": "ItemDelegate", "unnamed": 1, "visible": True}
invasive_Label = {"container": mainWindow_Overlay, "text": "Invasive", "type": "Label", "unnamed": 1, "visible": True}
sIMV_Label = {"container": mainWindow_Overlay, "text": "SIMV", "type": "Label", "unnamed": 1, "visible": True}
biLevel_Label = {"container": mainWindow_Overlay, "text": "BiLevel", "type": "Label", "unnamed": 1, "visible": True}
o_Trig_Label = {"container": mainWindow_Overlay, "text": "-Trig", "type": "Label", "unnamed": 1, "visible": True}
mainWindow_buttonBackground_Rectangle_6 = {"container": mainWindow_QQuickApplicationWindow, "id": "buttonBackground", "type": "Rectangle", "unnamed": 1, "visible": True}
mainWindow_alertsList_ListViewDragHandler = {"container": mainWindow_QQuickApplicationWindow, "id": "alertsList", "type": "ListViewDragHandler", "unnamed": 1, "visible": True}
alertsList_alertDelegate_AlertDialog = {"container": mainWindow_alertsList_ListViewDragHandler, "id": "alertDelegate", "index": 0, "type": "AlertDialog", "unnamed": 1, "visible": True}
alertDelegate_image_IconImage = {"container": alertsList_alertDelegate_AlertDialog, "objectName": "image", "source": "qrc:/images/icons/general/close.svg", "type": "IconImage", "visible": True}
mainWindow_flickable_Flickable_2 = {"container": mainWindow_QQuickApplicationWindow, "id": "flickable", "type": "Flickable", "unnamed": 1, "visible": True}
mainWindow_Rectangle_3 = {"container": mainWindow_QQuickApplicationWindow, "occurrence": 195, "type": "Rectangle", "unnamed": 1, "visible": True}
mainWindow_dialogBackground_Rectangle_2 = {"container": mainWindow_QQuickApplicationWindow, "id": "dialogBackground", "occurrence": 2, "type": "Rectangle", "unnamed": 1, "visible": True}
mainWindow_button_Button_8 = {"checkable": False, "container": mainWindow_QQuickApplicationWindow, "id": "button", "occurrence": 2, "type": "Button", "unnamed": 1, "visible": True}
mainWindow_backgroundRectangle_Rectangle = {"container": mainWindow_QQuickApplicationWindow, "id": "backgroundRectangle", "occurrence": 5, "type": "Rectangle", "unnamed": 1, "visible": True}
mainWindow_Continue_StyledButton_2 = {"checkable": False, "container": mainWindow_QQuickApplicationWindow, "id": "softBoundContinueButton", "text": "Continue", "type": "StyledButton", "unnamed": 1, "visible": True}
mainWindow_image_IconImage_2 = {"container": mainWindow_QQuickApplicationWindow, "objectName": "image", "source": "qrc:/images/icons/general/close.svg", "type": "IconImage", "visible": True}
mainWindow_closePopupButton_ToolButton = {"checkable": False, "container": mainWindow_QQuickApplicationWindow, "id": "closePopupButton", "type": "ToolButton", "unnamed": 1, "visible": True}
adult_Label = {"container": mainWindow_Overlay, "text": "Adult", "type": "Label", "unnamed": 1, "visible": True}
mainWindow_button_Button_9 = {"checkable": False, "container": mainWindow_QQuickApplicationWindow, "id": "button", "occurrence": 8, "type": "Button", "unnamed": 1, "visible": True}
flickable_image_IconImage = {"container": mainWindow_flickable_Flickable, "objectName": "image", "source": "qrc:/images/icons/configuration/delete_preset.svg", "type": "IconImage", "visible": True}
mainWindow_I_E_Ratio_indicates_the_ratio_of_inspiratory_time_to_expiratory_time_for_the_previous_breath_regardless_of_type_Due_to_limitations_in_setting_the_I_E_ratio_in_PC_ventilation_the_monitored_data_display_and_the_setting_may_not_match_precisely_I_E_Ratio_is_updated_at_the_beginning_of_the_next_inspiration_Label = {"container": mainWindow_QQuickApplicationWindow, "text": "I:E Ratio indicates the ratio of inspiratory time to expiratory time for the previous breath, regardless of type. Due to limitations in setting the I:E ratio in PC ventilation, the monitored data display and the setting may not match precisely. I:E Ratio is updated at the beginning of the next inspiration.", "type": "Label", "unnamed": 1, "visible": True}
mainWindow_parameterDescription_Flickable = {"container": mainWindow_QQuickApplicationWindow, "id": "parameterDescription", "type": "Flickable", "unnamed": 1, "visible": True}
mainWindow_parametersList_ListViewDragHandler = {"container": mainWindow_QQuickApplicationWindow, "id": "parametersList", "type": "ListViewDragHandler", "unnamed": 1, "visible": True}
parametersList_listDelegate_ParameterSelectionPanelListDelegate = {"container": mainWindow_parametersList_ListViewDragHandler, "id": "listDelegate", "index": 7, "type": "ParameterSelectionPanelListDelegate", "unnamed": 1, "visible": True}
listDelegate_Total_Respiratory_Rate_Label = {"container": parametersList_listDelegate_ParameterSelectionPanelListDelegate, "text": "Total Respiratory Rate", "type": "Label", "unnamed": 1, "visible": True}
parametersList_listDelegate_ParameterSelectionPanelListDelegate_2 = {"container": mainWindow_parametersList_ListViewDragHandler, "id": "listDelegate", "index": 11, "type": "ParameterSelectionPanelListDelegate", "unnamed": 1, "visible": True}
listDelegate_Intrinsic_PEEP_Label = {"container": parametersList_listDelegate_ParameterSelectionPanelListDelegate_2, "text": "Intrinsic PEEP", "type": "Label", "unnamed": 1, "visible": True}
parametersList_listDelegate_ParameterSelectionPanelListDelegate_3 = {"container": mainWindow_parametersList_ListViewDragHandler, "id": "listDelegate", "index": 9, "type": "ParameterSelectionPanelListDelegate", "unnamed": 1, "visible": True}
listDelegate_delegateBackground_Rectangle = {"container": parametersList_listDelegate_ParameterSelectionPanelListDelegate_3, "id": "delegateBackground", "type": "Rectangle", "unnamed": 1, "visible": True}
listDelegate_delegateBackground_Rectangle_2 = {"container": parametersList_listDelegate_ParameterSelectionPanelListDelegate, "id": "delegateBackground", "type": "Rectangle", "unnamed": 1, "visible": True}
